name: NSE Swing Scanner

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pandas numpy requests beautifulsoup4
      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FYERS_CLIENT_ID: ${{ secrets.FYERS_CLIENT_ID }}
          FYERS_SECRET_KEY: ${{ secrets.FYERS_SECRET_KEY }}
        run: python scanner.py
