name: NSE Swing Scanner

on:
  workflow_dispatch:

  schedule:
    - cron: "15 10 * * 1-5"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests beautifulsoup4 pandas

      - name: Check files
        run: |
          echo "Files in repository:"
          ls -la
          echo "Workflow directory:"
          ls -la .github/workflows

      - name: Run Scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python scanner.py
